import { GP011_KNOWLEDGE } from "./knowledge/index.js"; import { GP011_POLICIES, GP011_PROMPT, GP011_WORKFLOW } from "./definition.js"; import { validateGP011Input, validateGP011Output } from "./validator.js"; import { runPDPAWorkflow } from "./workflow.js"; import { formatGP011Output } from "./output-engine.js";
export class GP011Module {
  #core; #copilots;
  constructor(dependencies) { const names = Array.from({ length: 10 }, (_, index) => `gp${String(index + 1).padStart(3, "0")}`); for (const name of ["contextManager", "router", "promptRegistry", "knowledgeRegistry", "governance", "observability", ...names]) if (!dependencies?.[name]) throw new TypeError(`GP011 dependency is required: ${name}`); this.#core = dependencies; this.#copilots = Object.fromEntries(names.map((name) => [name, dependencies[name]])); this.#bootstrap(); }
  async execute(rawInput) { return this.#core.observability.runInTrace("gp011.execute", async () => { const stop = this.#core.observability.startTimer("gp011.execution.duration", { template: rawInput?.template ?? "unknown" }); this.#core.observability.increment("gp011.requests.total"); try {
    const input = validateGP011Input(rawInput); const route = this.#core.router.routeRequest(`GP011 PDPA privacy personal data ${input.processing.purpose}`); if (route.primaryModule !== "GP011") throw new Error("Transaction Router did not select GP011");
    const knowledge = this.#core.knowledgeRegistry.search("", { language: input.language, minConfidence: 0.7 }).filter(({ id }) => id.startsWith("gp011-")); for (const entry of knowledge) if (this.#core.governance.authorizeKnowledge(entry, input.principal).status !== "allowed") throw new Error(`Knowledge authorization failed: ${entry.id}`);
    const crossModule = {}; for (const [key, copilot] of Object.entries(this.#copilots)) if (input.linkedReviews[key]) crossModule[key] = await copilot.execute(input.linkedReviews[key]);
    this.#core.contextManager.switchModule("GP011"); const prompt = this.#core.promptRegistry.getPrompt("GP011", GP011_PROMPT.version); if (this.#core.governance.authorizePrompt(prompt, input.principal, { processingId: input.processing.id }).status !== "allowed") throw new Error("GP011 prompt authorization failed");
    const result = runPDPAWorkflow(input, crossModule); validateGP011Output(result); if (!result.approval.ready) { const evidence = { processingId: input.processing.id, missing: result.approval.missing, risk: result.risk }; this.#core.observability.increment("gp011.approvals.required"); this.#core.observability.emitAudit("gp011.approval_required", evidence); stop("approval_required"); return { status: "approval_required", moduleId: "GP011", approval: result.approval, analysis: result }; }
    const resolved = this.#core.promptRegistry.resolvePrompt("GP011", { processing: input.processing.purpose, date: input.asOfDate, knowledge: knowledge.map(({ title }) => title).join("; "), template: input.template, outputFormat: input.outputFormat }, { version: GP011_PROMPT.version }); const audit = { promptVersion: resolved.definition.version, workflow: GP011_WORKFLOW, knowledgeIds: knowledge.map(({ id }) => id), linkedModules: Object.keys(crossModule), compliant: result.report.status === "compliant", risk: result.risk };
    const output = formatGP011Output(result, input.outputFormat, audit); this.#core.contextManager.updateContext((context) => ({ workflowState: { module: "GP011", step: "completed", processingId: input.processing.id, complianceStatus: result.report.status }, userSelections: { ...context.userSelections, gp011Template: input.template }, legalReferences: knowledge.map(({ id, title, metadata }) => ({ id, title, authority: metadata.authority, version: metadata.version })) })); this.#core.observability.increment("gp011.completed.total", 1, { risk: result.risk.level }); this.#core.observability.emitAudit("gp011.completed", audit); stop("ok"); return { status: "completed", moduleId: "GP011", promptVersion: GP011_PROMPT.version, analysis: result, output };
  } catch (error) { this.#core.observability.increment("gp011.failed.total"); this.#core.observability.captureError(error, { moduleId: "GP011" }); stop("error"); throw error; } }); }
  #bootstrap() { const { promptRegistry, knowledgeRegistry, governance } = this.#core; if (!promptRegistry.getPrompt("GP011", GP011_PROMPT.version)) promptRegistry.registerPrompt(GP011_PROMPT); for (const entry of GP011_KNOWLEDGE) if (!knowledgeRegistry.getKnowledge(entry.id, entry.metadata.version)) knowledgeRegistry.registerKnowledge(entry); const existing = new Set(governance.getPolicySnapshot().map(({ id, version }) => `${id}@${version}`)); for (const policy of GP011_POLICIES) if (!existing.has(`${policy.id}@${policy.version}`)) governance.registerPolicy(policy); }
}
