import { detectPDPA } from "./pdpa-engine.js"; import { autoMask } from "./masking-engine.js"; import { validateConsent } from "./consent-engine.js"; import { assessRetention } from "./retention-engine.js"; import { reviewDisclosure, assessSharing } from "./disclosure-engine.js"; import { scorePrivacyRisk } from "./risk-engine.js"; import { buildComplianceChecklist, buildAuditEvidence } from "./audit-engine.js";
export function runPDPAWorkflow(input, crossModule = {}) {
  const detection = detectPDPA(input.records); const masking = autoMask(input.records, detection); const consent = validateConsent(input, detection); const disclosure = reviewDisclosure(input); const retention = assessRetention(input); const sharing = assessSharing(input);
  const parts = { processing: input.processing, detection, masking, consent, disclosure, retention, sharing }; const risk = scorePrivacyRisk(parts); const checklist = buildComplianceChecklist({ ...parts, risk });
  const linkedIncomplete = Object.entries(crossModule).filter(([, result]) => result?.status !== "completed").map(([id]) => id).sort(); const requiredRoles = [...new Set([...(detection.sensitiveCount ? ["data-protection-officer"] : []), ...(risk.level === "high" ? ["supervisor"] : [])])]; const approval = { required: requiredRoles.length > 0, requiredRoles, grantedRoles: [...input.approvals].sort(), missing: requiredRoles.filter((role) => !input.approvals.includes(role)), ready: requiredRoles.every((role) => input.approvals.includes(role)) };
  const audit = buildAuditEvidence(input, { ...parts, risk, checklist }, crossModule); const status = checklist.compliant && approval.ready && linkedIncomplete.length === 0 ? "compliant" : "review-required";
  const report = { processingId: input.processing.id, purpose: input.processing.purpose, controller: input.processing.controller ?? null, status, detectedTypes: detection.types, riskLevel: risk.level, riskScore: risk.score, controlsPassed: `${checklist.passed}/${checklist.total}`, linkedIncomplete, recommendations: [...(!consent.valid ? ["establish-valid-lawful-basis"] : []), ...(!retention.valid ? ["define-retention-and-disposal"] : []), ...(!disclosure.valid ? ["remediate-disclosure-controls"] : []), ...(!sharing.valid ? ["formalize-data-sharing"] : []), ...(masking.unresolvedSensitive.length ? ["review-sensitive-data"] : [])] };
  return { template: input.template, detection, masking, consent, disclosure, retention, sharing, risk, checklist, approval, audit, report, crossModule };
}
