import test from "node:test";
import assert from "node:assert/strict";
import { ContextManager } from "../../src/context-manager.js"; import { TransactionRouter } from "../../src/transaction-router.js"; import { PromptRegistry } from "../../src/prompt-registry.js"; import { KnowledgeRegistry } from "../../src/knowledge-registry.js"; import { GovernanceLayer } from "../../src/governance-layer.js"; import { Observability } from "../../src/observability.js";
import { GP002Module } from "../../src/modules/gp002/gp002-module.js"; import { GP003Module } from "../../src/modules/gp003/gp003-module.js"; import { GP004Module } from "../../src/modules/gp004/gp004-module.js"; import { GP005Module } from "../../src/modules/gp005/gp005-module.js"; import { GP006Module } from "../../src/modules/gp006/gp006-module.js";

function runtime() {
  const contextManager = new ContextManager(); const core = { contextManager, router: new TransactionRouter(contextManager), promptRegistry: new PromptRegistry(contextManager), knowledgeRegistry: new KnowledgeRegistry(contextManager), governance: new GovernanceLayer(contextManager), observability: new Observability(contextManager) };
  const lawCopilot = new GP002Module(core); const procurementCopilot = new GP003Module(core); const financeCopilot = new GP004Module({ ...core, lawCopilot, procurementCopilot }); const budgetCopilot = new GP005Module({ ...core, lawCopilot, procurementCopilot, financeCopilot });
  return { ...core, lawCopilot, financeCopilot, budgetCopilot, gp006: new GP006Module({ ...core, lawCopilot, financeCopilot, budgetCopilot }) };
}
const base = (overrides = {}) => ({ action: "promotion", position: { id: "analyst-senior", vacant: true, requiredQualifications: ["degree", "license"], allowanceEligible: true, allowanceCap: 5000 }, candidate: { qualifications: ["degree", "license"], selectionPassed: true, appointmentAuthorityApproved: true }, promotion: { tenureYears: 5, minimumTenureYears: 3, performanceScore: 90, minimumPerformanceScore: 80 }, discipline: { activeCase: false }, employee: { birthDate: "1980-01-01", retirementAge: 60 }, salary: { current: 30000, increment: 1000, maximum: 40000, performanceEligible: true }, workforce: { authorized: 10, filled: 8 }, template: "promotion-analysis", outputFormat: "json", principal: { id: "hr-1", role: "hr-officer" }, ...overrides });
test("registers prompt, workflow, templates, policies, and knowledge idempotently", () => { const r = runtime(); new GP006Module(r); assert.equal(r.promptRegistry.getPrompt("GP006", "2.0.0").metadata.owner, "government-hr-team"); assert.equal(r.knowledgeRegistry.search("", {}).filter(({ id }) => id.startsWith("gp006-")).length, 10); });
test("executes deterministic HR workflow through Sprint 1 Core", async () => { const r = runtime(); const a = await r.gp006.execute(base()); const b = await r.gp006.execute(base()); assert.equal(a.status, "completed"); assert.deepEqual(a.analysis, b.analysis); assert.equal(a.analysis.promotion.eligible, true); assert.equal(r.contextManager.getContext().activeModule, "GP006"); assert.ok(r.observability.getAuditEvents().some(({ type }) => type === "gp006.completed")); });
test("integrates GP002, GP004, and GP005 completed reviews", async () => {
  const r = runtime(); const result = await r.gp006.execute(base({
    legalReviewInput: { facts: "Promotion follows personnel rules.", question: "Is authority established?", template: "executive-summary", outputFormat: "json", principal: { id: "l1", role: "legal-officer" } },
    financeReviewInput: { purpose: "Position allowance", financeType: "house-rental", requestedAmount: 100, budgetAllocated: 1000, budgetCommitted: 0, employee: { status: "officer" }, approvals: ["supervisor"], documents: { budgetCertification: true }, template: "finance-opinion", outputFormat: "json", principal: { id: "f1", role: "finance-officer" } },
    budgetReviewInput: { purpose: "Personnel appropriation", classification: "personnel", allocated: 1000, spent: 0, committed: 0, requestedAmount: 100, ordinance: { approved: true, appropriatedAmount: 1000 }, developmentPlan: { projectId: "p", localProjectIds: ["p"], strategicProjectIds: ["p"] }, documents: { budgetCertification: true }, template: "budget-opinion", outputFormat: "json", principal: { id: "b1", role: "budget-officer" } },
  }));
  assert.deepEqual(Object.fromEntries(Object.entries(result.analysis.hr.crossModule).map(([k, v]) => [k, v.status])), { legal: "completed", finance: "completed", budget: "completed" }); assert.equal(r.contextManager.getContext().activeModule, "GP006");
});
test("supports Markdown, audit, and API output", async () => { const r = runtime(); const m = await r.gp006.execute(base({ outputFormat: "markdown" })); const a = await r.gp006.execute(base({ outputFormat: "audit-log" })); const api = await r.gp006.execute(base({ outputFormat: "api-response" })); assert.match(m.output, /^# Promotion Analysis/); assert.equal(a.output.event, "gp006.hr-analysis"); assert.equal(api.output.ok, true); });
