import test from "node:test"; import assert from "node:assert/strict";
import { ContextManager } from "../../src/context-manager.js"; import { TransactionRouter } from "../../src/transaction-router.js"; import { PromptRegistry } from "../../src/prompt-registry.js"; import { KnowledgeRegistry } from "../../src/knowledge-registry.js"; import { GovernanceLayer } from "../../src/governance-layer.js"; import { Observability } from "../../src/observability.js";
import { GP002Module } from "../../src/modules/gp002/gp002-module.js"; import { GP003Module } from "../../src/modules/gp003/gp003-module.js"; import { GP004Module } from "../../src/modules/gp004/gp004-module.js"; import { GP005Module } from "../../src/modules/gp005/gp005-module.js"; import { GP006Module } from "../../src/modules/gp006/gp006-module.js"; import { GP007Module } from "../../src/modules/gp007/gp007-module.js";
function runtime() { const contextManager = new ContextManager(); const core = { contextManager, router: new TransactionRouter(contextManager), promptRegistry: new PromptRegistry(contextManager), knowledgeRegistry: new KnowledgeRegistry(contextManager), governance: new GovernanceLayer(contextManager), observability: new Observability(contextManager) }; const lawCopilot = new GP002Module(core); const procurementCopilot = new GP003Module(core); const financeCopilot = new GP004Module({ ...core, lawCopilot, procurementCopilot }); const budgetCopilot = new GP005Module({ ...core, lawCopilot, procurementCopilot, financeCopilot }); const hrCopilot = new GP006Module({ ...core, lawCopilot, financeCopilot, budgetCopilot }); return { ...core, lawCopilot, budgetCopilot, hrCopilot, gp007: new GP007Module({ ...core, lawCopilot, budgetCopilot, hrCopilot }) }; }
const base = (overrides = {}) => ({ councilType: "municipal", subject: "Approve development project", totalMembers: 10, agendaItems: [{ title: "Development project", documentsComplete: true, withinAuthority: true }], motion: { text: "Approve the project", proposer: "member-1", seconder: "member-2", withinAgenda: true, withinJurisdiction: true }, attendance: Array.from({ length: 6 }, (_, i) => ({ memberId: `m${i}`, present: true })), voting: { yes: 4, no: 2, abstain: 0, rule: "simple-majority" }, meeting: { noticeDays: 3, minimumNoticeDays: 3, minutesRecorded: true, resolutionNumber: "1/2026", minutesApproved: true }, bylaw: {}, template: "motion-review", outputFormat: "json", principal: { id: "secretary-1", role: "council-secretary" }, ...overrides });
test("registers prompt, workflow, templates, policies, and knowledge idempotently", () => { const r = runtime(); new GP007Module(r); assert.equal(r.promptRegistry.getPrompt("GP007", "2.0.0").metadata.owner, "government-council-team"); assert.equal(r.knowledgeRegistry.search("", {}).filter(({ id }) => id.startsWith("gp007-")).length, 8); });
test("executes deterministic council workflow through Sprint 1 Core", async () => { const r = runtime(); const a = await r.gp007.execute(base()); const b = await r.gp007.execute(base()); assert.equal(a.status, "completed"); assert.deepEqual(a.analysis, b.analysis); assert.equal(a.analysis.council.resolutionValid, true); assert.equal(r.contextManager.getContext().activeModule, "GP007"); assert.ok(r.observability.getAuditEvents().some(({ type }) => type === "gp007.completed")); });
test("integrates completed GP002, GP005, and GP006 reviews", async () => { const r = runtime(); const result = await r.gp007.execute(base({
  legalReviewInput: { facts: "Council considers a municipal resolution.", question: "Is authority established?", template: "executive-summary", outputFormat: "json", principal: { id: "l1", role: "legal-officer" } },
  budgetReviewInput: { purpose: "Council project", classification: "investment", allocated: 1000, spent: 0, committed: 0, requestedAmount: 100, ordinance: { approved: true, appropriatedAmount: 1000 }, developmentPlan: { projectId: "p", localProjectIds: ["p"], strategicProjectIds: ["p"] }, documents: { budgetCertification: true }, template: "budget-opinion", outputFormat: "json", principal: { id: "b1", role: "budget-officer" } },
  hrReviewInput: { action: "qualification", position: { id: "secretary", requiredQualifications: ["degree"] }, candidate: { qualifications: ["degree"] }, template: "executive-summary", outputFormat: "json", totalMembers: 1, principal: { id: "h1", role: "hr-officer" } },
})); assert.deepEqual(Object.fromEntries(Object.entries(result.analysis.crossModule).map(([k, v]) => [k, v.status])), { legal: "completed", budget: "completed", hr: "completed" }); assert.equal(r.contextManager.getContext().activeModule, "GP007"); });
test("supports Markdown, audit, and API output", async () => { const r = runtime(); const m = await r.gp007.execute(base({ outputFormat: "markdown" })); const a = await r.gp007.execute(base({ outputFormat: "audit-log" })); const api = await r.gp007.execute(base({ outputFormat: "api-response" })); assert.match(m.output, /^# Motion Review/); assert.equal(a.output.event, "gp007.council-analysis"); assert.equal(api.output.ok, true); });
