import { GP008_KNOWLEDGE } from "./knowledge/index.js"; import { GP008_POLICIES, GP008_PROMPT, GP008_WORKFLOW } from "./definition.js"; import { validateGP008Input, validateGP008Output } from "./validator.js"; import { runProjectWorkflow } from "./workflow.js"; import { formatGP008Output } from "./output-engine.js";
export class GP008Module {
  #core; #copilots;
  constructor(dependencies) { for (const name of ["contextManager", "router", "promptRegistry", "knowledgeRegistry", "governance", "observability", "lawCopilot", "procurementCopilot", "financeCopilot", "budgetCopilot", "councilCopilot"]) if (!dependencies?.[name]) throw new TypeError(`GP008 dependency is required: ${name}`); this.#core = dependencies; this.#copilots = { legal: dependencies.lawCopilot, procurement: dependencies.procurementCopilot, finance: dependencies.financeCopilot, budget: dependencies.budgetCopilot, council: dependencies.councilCopilot }; this.#bootstrap(); }
  async execute(rawInput) { return this.#core.observability.runInTrace("gp008.execute", async () => { const stop = this.#core.observability.startTimer("gp008.execution.duration", { template: rawInput?.template ?? "unknown" }); this.#core.observability.increment("gp008.requests.total"); try {
    const input = validateGP008Input(rawInput); const route = this.#core.router.routeRequest(`GP008 project proposal ${input.project.name}`); if (route.primaryModule !== "GP008") throw new Error("Transaction Router did not select GP008");
    const knowledge = this.#core.knowledgeRegistry.search("", { language: input.language, minConfidence: 0.7 }).filter(({ id }) => id.startsWith("gp008-")); for (const entry of knowledge) if (this.#core.governance.authorizeKnowledge(entry, input.principal).status !== "allowed") throw new Error(`Knowledge authorization failed: ${entry.id}`);
    const crossModule = {}; for (const [key, copilot] of Object.entries(this.#copilots)) { const reviewInput = input[`${key}ReviewInput`]; if (reviewInput) crossModule[key] = await copilot.execute(reviewInput); }
    this.#core.contextManager.switchModule("GP008"); const prompt = this.#core.promptRegistry.getPrompt("GP008", GP008_PROMPT.version); if (this.#core.governance.authorizePrompt(prompt, input.principal, { project: input.project.name }).status !== "allowed") throw new Error("GP008 prompt authorization failed");
    const result = runProjectWorkflow(input, crossModule); validateGP008Output(result); const resolved = this.#core.promptRegistry.resolvePrompt("GP008", { project: input.project.name, objective: input.project.objective, knowledge: knowledge.map(({ title }) => title).join("; "), template: input.template, outputFormat: input.outputFormat }, { version: GP008_PROMPT.version });
    const audit = { promptVersion: resolved.definition.version, workflow: GP008_WORKFLOW, knowledgeIds: knowledge.map(({ id }) => id), linkedModules: Object.keys(crossModule), decision: result.project.decision, risk: result.risk }; const output = formatGP008Output(result, input.outputFormat, audit);
    this.#core.contextManager.updateContext((context) => ({ workflowState: { module: "GP008", step: "completed", project: input.project.name }, userSelections: { ...context.userSelections, gp008Template: input.template }, procurementAndBudgetContext: { ...context.procurementAndBudgetContext, project: input.project.name, projectBudget: input.project.budget, projectBudgetConsistent: result.budget.consistent }, legalReferences: knowledge.map(({ id, title, metadata }) => ({ id, title, authority: metadata.authority, version: metadata.version })) }));
    this.#core.observability.increment("gp008.completed.total", 1, { template: input.template }); this.#core.observability.emitAudit("gp008.completed", audit); stop("ok"); return { status: "completed", moduleId: "GP008", promptVersion: GP008_PROMPT.version, analysis: result, output };
  } catch (error) { this.#core.observability.increment("gp008.failed.total"); this.#core.observability.captureError(error, { moduleId: "GP008" }); stop("error"); throw error; } }); }
  #bootstrap() { const { promptRegistry, knowledgeRegistry, governance } = this.#core; if (!promptRegistry.getPrompt("GP008", GP008_PROMPT.version)) promptRegistry.registerPrompt(GP008_PROMPT); for (const entry of GP008_KNOWLEDGE) if (!knowledgeRegistry.getKnowledge(entry.id, entry.metadata.version)) knowledgeRegistry.registerKnowledge(entry); const existing = new Set(governance.getPolicySnapshot().map(({ id, version }) => `${id}@${version}`)); for (const policy of GP008_POLICIES) if (!existing.has(`${policy.id}@${policy.version}`)) governance.registerPolicy(policy); }
}
