import { GP010_KNOWLEDGE } from "./knowledge/index.js"; import { GP010_POLICIES, GP010_PROMPT, GP010_WORKFLOW } from "./definition.js"; import { validateGP010Input, validateGP010Output } from "./validator.js"; import { runMeetingWorkflow } from "./workflow.js"; import { formatGP010Output } from "./output-engine.js";
export class GP010Module {
  #core; #copilots;
  constructor(dependencies) { const moduleNames = Array.from({ length: 9 }, (_, index) => `gp${String(index + 1).padStart(3, "0")}`); for (const name of ["contextManager", "router", "promptRegistry", "knowledgeRegistry", "governance", "observability", ...moduleNames]) if (!dependencies?.[name]) throw new TypeError(`GP010 dependency is required: ${name}`); this.#core = dependencies; this.#copilots = Object.fromEntries(moduleNames.map((name) => [name, dependencies[name]])); this.#bootstrap(); }
  async execute(rawInput) { return this.#core.observability.runInTrace("gp010.execute", async () => { const stop = this.#core.observability.startTimer("gp010.execution.duration", { template: rawInput?.template ?? "unknown" }); this.#core.observability.increment("gp010.requests.total"); try {
    const input = validateGP010Input(rawInput); const route = this.#core.router.routeRequest(`GP010 meeting minutes agenda ${input.meeting.title}`); if (route.primaryModule !== "GP010") throw new Error("Transaction Router did not select GP010");
    const knowledge = this.#core.knowledgeRegistry.search("", { language: input.language, minConfidence: 0.7 }).filter(({ id }) => id.startsWith("gp010-")); for (const entry of knowledge) if (this.#core.governance.authorizeKnowledge(entry, input.principal).status !== "allowed") throw new Error(`Knowledge authorization failed: ${entry.id}`);
    const crossModule = {}; for (const [key, copilot] of Object.entries(this.#copilots)) { const reviewInput = input.linkedReviews[key]; if (reviewInput) crossModule[key] = await copilot.execute(reviewInput); }
    this.#core.contextManager.switchModule("GP010"); const prompt = this.#core.promptRegistry.getPrompt("GP010", GP010_PROMPT.version); if (this.#core.governance.authorizePrompt(prompt, input.principal, { meetingId: input.meeting.id }).status !== "allowed") throw new Error("GP010 prompt authorization failed");
    const result = runMeetingWorkflow(input, crossModule); validateGP010Output(result); const resolved = this.#core.promptRegistry.resolvePrompt("GP010", { meeting: input.meeting.title, date: input.meeting.date, knowledge: knowledge.map(({ title }) => title).join("; "), template: input.template, outputFormat: input.outputFormat }, { version: GP010_PROMPT.version });
    const audit = { promptVersion: resolved.definition.version, workflow: GP010_WORKFLOW, knowledgeIds: knowledge.map(({ id }) => id), linkedModules: Object.keys(crossModule), packageReady: result.package.ready }; const output = formatGP010Output(result, input.outputFormat, audit);
    this.#core.contextManager.updateContext((context) => ({ workflowState: { module: "GP010", step: "completed", meetingId: input.meeting.id }, userSelections: { ...context.userSelections, gp010Template: input.template }, legalReferences: knowledge.map(({ id, title, metadata }) => ({ id, title, authority: metadata.authority, version: metadata.version })) }));
    this.#core.observability.increment("gp010.completed.total", 1, { template: input.template }); this.#core.observability.emitAudit("gp010.completed", audit); stop("ok"); return { status: "completed", moduleId: "GP010", promptVersion: GP010_PROMPT.version, analysis: result, output };
  } catch (error) { this.#core.observability.increment("gp010.failed.total"); this.#core.observability.captureError(error, { moduleId: "GP010" }); stop("error"); throw error; } }); }
  #bootstrap() { const { promptRegistry, knowledgeRegistry, governance } = this.#core; if (!promptRegistry.getPrompt("GP010", GP010_PROMPT.version)) promptRegistry.registerPrompt(GP010_PROMPT); for (const entry of GP010_KNOWLEDGE) if (!knowledgeRegistry.getKnowledge(entry.id, entry.metadata.version)) knowledgeRegistry.registerKnowledge(entry); const existing = new Set(governance.getPolicySnapshot().map(({ id, version }) => `${id}@${version}`)); for (const policy of GP010_POLICIES) if (!existing.has(`${policy.id}@${policy.version}`)) governance.registerPolicy(policy); }
}
