import { buildAgenda } from "./agenda-engine.js"; import { validateAttendance } from "./attendance-engine.js"; import { generateMinutes } from "./minutes-engine.js"; import { draftResolutions } from "./resolution-engine.js"; import { buildActions } from "./action-engine.js"; import { buildFollowup } from "./followup-engine.js"; import { buildDecisionRegister } from "./decision-engine.js";
export function runMeetingWorkflow(input, crossModule = {}) {
  const agenda = buildAgenda(input); const attendance = validateAttendance(input.participants); const minutes = generateMinutes(input, agenda, attendance); const resolutions = draftResolutions(input, agenda); const actions = buildActions(input); const followup = buildFollowup(input, actions); const decisions = buildDecisionRegister(input, resolutions);
  const gaps = [...(!agenda.complete ? ["agenda-incomplete"] : []), ...(!attendance.valid ? ["attendance-invalid"] : []), ...(!minutes.complete ? ["minutes-incomplete"] : []), ...(!resolutions.valid ? ["resolution-invalid"] : []), ...(!actions.valid ? ["action-invalid"] : []), ...Object.entries(crossModule).filter(([, value]) => value?.status !== "completed").map(([key]) => `${key}-review-incomplete`)];
  const summary = { meetingId: input.meeting.id, title: input.meeting.title, date: input.meeting.date, agendaItems: agenda.items.length, participantsPresent: attendance.present, resolutions: resolutions.count, openActions: actions.openCount, overdueActions: followup.overdueCount, status: gaps.length ? "review-required" : "complete", gaps };
  const audit = { meetingId: input.meeting.id, checks: ["agenda", "attendance", "minutes", "resolutions", "actions", "followup", "decisions"], valid: gaps.length === 0, linkedModules: Object.keys(crossModule) };
  const packageResult = { ready: gaps.length === 0, assets: ["agenda", "minutes", "resolutions", "attendance", "actions", "followup", "decision-register", "reminders", "audit"], exportId: input.exportId ?? input.meeting.id };
  return { template: input.template, agenda, attendance, minutes, resolutions, actions, followup, decisions, summary, audit, package: packageResult, crossModule };
}
