import { GP009_KNOWLEDGE } from "./knowledge/index.js"; import { GP009_POLICIES, GP009_PROMPT, GP009_WORKFLOW } from "./definition.js"; import { validateGP009Input, validateGP009Output } from "./validator.js"; import { runPRWorkflow } from "./workflow.js"; import { formatGP009Output } from "./output-engine.js";
export class GP009Module {
  #core; #copilots;
  constructor(dependencies) { for (const name of ["contextManager", "router", "promptRegistry", "knowledgeRegistry", "governance", "observability", "lawCopilot", "procurementCopilot", "financeCopilot", "budgetCopilot", "councilCopilot", "projectCopilot"]) if (!dependencies?.[name]) throw new TypeError(`GP009 dependency is required: ${name}`); this.#core = dependencies; this.#copilots = { legal: dependencies.lawCopilot, procurement: dependencies.procurementCopilot, finance: dependencies.financeCopilot, budget: dependencies.budgetCopilot, council: dependencies.councilCopilot, project: dependencies.projectCopilot }; this.#bootstrap(); }
  async execute(rawInput) { return this.#core.observability.runInTrace("gp009.execute", async () => { const stop = this.#core.observability.startTimer("gp009.execution.duration", { template: rawInput?.template ?? "unknown" }); this.#core.observability.increment("gp009.requests.total"); try {
    const input = validateGP009Input(rawInput); const route = this.#core.router.routeRequest(`GP009 public relations communication ${input.subject}`); if (route.primaryModule !== "GP009") throw new Error("Transaction Router did not select GP009");
    const knowledge = this.#core.knowledgeRegistry.search("", { language: input.language, minConfidence: 0.7 }).filter(({ id }) => id.startsWith("gp009-")); for (const entry of knowledge) if (this.#core.governance.authorizeKnowledge(entry, input.principal).status !== "allowed") throw new Error(`Knowledge authorization failed: ${entry.id}`);
    const crossModule = {}; for (const [key, copilot] of Object.entries(this.#copilots)) { const reviewInput = input[`${key}ReviewInput`]; if (reviewInput) crossModule[key] = await copilot.execute(reviewInput); }
    this.#core.contextManager.switchModule("GP009"); const prompt = this.#core.promptRegistry.getPrompt("GP009", GP009_PROMPT.version); if (this.#core.governance.authorizePrompt(prompt, input.principal, { subject: input.subject }).status !== "allowed") throw new Error("GP009 prompt authorization failed");
    const result = runPRWorkflow(input, crossModule); validateGP009Output(result);
    if (!result.approval.ready) { this.#core.observability.increment("gp009.approvals.required"); this.#core.observability.emitAudit("gp009.approval_required", { missing: result.approval.missing, subject: input.subject }); stop("approval_required"); return { status: "approval_required", moduleId: "GP009", approval: result.approval, analysis: result }; }
    const resolved = this.#core.promptRegistry.resolvePrompt("GP009", { template: input.template, subject: input.subject, audience: input.audience, knowledge: knowledge.map(({ title }) => title).join("; "), outputFormat: input.outputFormat }, { version: GP009_PROMPT.version });
    const audit = { promptVersion: resolved.definition.version, workflow: GP009_WORKFLOW, knowledgeIds: knowledge.map(({ id }) => id), linkedModules: Object.keys(crossModule), publicationReady: result.package.ready }; const output = formatGP009Output(result, input.outputFormat, audit);
    this.#core.contextManager.updateContext((context) => ({ workflowState: { module: "GP009", step: "completed", publicationReady: result.package.ready }, userSelections: { ...context.userSelections, gp009Template: input.template, gp009Channels: input.channels }, legalReferences: knowledge.map(({ id, title, metadata }) => ({ id, title, authority: metadata.authority, version: metadata.version })) }));
    this.#core.observability.increment("gp009.completed.total", 1, { template: input.template }); this.#core.observability.emitAudit("gp009.completed", audit); stop("ok"); return { status: "completed", moduleId: "GP009", promptVersion: GP009_PROMPT.version, analysis: result, output };
  } catch (error) { this.#core.observability.increment("gp009.failed.total"); this.#core.observability.captureError(error, { moduleId: "GP009" }); stop("error"); throw error; } }); }
  #bootstrap() { const { promptRegistry, knowledgeRegistry, governance } = this.#core; if (!promptRegistry.getPrompt("GP009", GP009_PROMPT.version)) promptRegistry.registerPrompt(GP009_PROMPT); for (const entry of GP009_KNOWLEDGE) if (!knowledgeRegistry.getKnowledge(entry.id, entry.metadata.version)) knowledgeRegistry.registerKnowledge(entry); const existing = new Set(governance.getPolicySnapshot().map(({ id, version }) => `${id}@${version}`)); for (const policy of GP009_POLICIES) if (!existing.has(`${policy.id}@${policy.version}`)) governance.registerPolicy(policy); }
}
